### ISSUE TITLE
0.1.0 Todo List

### ISSUE THREAD

**Issue by sijad** [sijad/gentle#1]
### Gentc CLI

- [ ] create `server.go` with `init` command
	* try only import all codes from generated or gentle/graphql package

### Code Generating

- [ ] introspection
- [ ] generate correct marshalers
- [ ] generate correct args unmarshalers
- [ ] write tests
- [ ] implement interfaces using Go interfaces + adding it to the struct
- [ ] implement subscriptions
- [ ] types and fields comments
- [ ] ability to deprecate using comments (similar to Go)
- [ ] remove `NONNULL` type (add `IsNull` prop to the type ref or add `NULLABLE` type)
- [ ] investigate how to generate same code and SDL
    * we can sort elements alphabetically
- [ ] cleanup `ImportType()` and remove inline functions
    * we probably can scan packages and export all fulltypes (enums, inputs and objects) first
    * then scan root objects and build the type refs tree
- [ ] ability to merge and use multiple root objects (`Query`, `Mutation`)
- [ ] don't allow none methods fields in root objects
    * makes it easier to implement introspection
    * makes it clear to run the server
- [ ] investigate ability to mark objects as input if they appears only as args
- [ ] specify types for basic types (int, string, uint32, etc)
- [ ] better errors with line number of the code
- [ ] cleanup code generating

**Comment by redbar0n** [comment]
This library looks very promising! I see that development stopped in Sept 2020. Why is that? Did you find an alternative?

**Comment by sijad** [comment]
please check out https://github.com/mjarkk/go-graphql

**Comment by voslartomas** [comment]
@sijad So you are abandoning this repository and working on `go-graphql` which will have similar approach?

**Comment by voslartomas** [comment]
Are you going to support Federation as well??

**Comment by sijad** [comment]
@voslartomas ATM I'm not sure if i going to continue I've suggested `mjarkk/go-graphql` because it's very similar project
